// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllYCuFj9NlYZgcR6DZUEQAfFJ5mqeksQ',
    appId: '1:154135530073:web:7e19922c2a911f6a18ff48',
    messagingSenderId: '154135530073',
    projectId: 'chat-app-a9f53',
    authDomain: 'chat-app-a9f53.firebaseapp.com',
    storageBucket: 'chat-app-a9f53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFexDNaK2lDuAxlt4upVD5jojwvPoyqr0',
    appId: '1:154135530073:android:fe290bda8f24996b18ff48',
    messagingSenderId: '154135530073',
    projectId: 'chat-app-a9f53',
    storageBucket: 'chat-app-a9f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA24XcT9m2ERd4posdHok0jT5Or6w5kG9I',
    appId: '1:154135530073:ios:34705ed8dc012baf18ff48',
    messagingSenderId: '154135530073',
    projectId: 'chat-app-a9f53',
    storageBucket: 'chat-app-a9f53.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
